# Header
menu:
  Home: /
  Code: categories/Code
  Read: categories/Read
  Life: categories/Life
  English: categories/Media
  Tags: javascript:;
  Docs: archives

# Content
excerpt_link: more

# Sidebar
author:
  name: Steven
  work: Coder &amp; A life learner
  location: Beijing, China
  avatar_url: https://upload.jianshu.io/users/upload_avatars/3098335/79645466-8cb0-4d4a-b855-3f80a8c86a50.jpg?imageMogr2/auto-orient/strip|imageView2/1/w/240/h/240

links:
  github: https://github.com/lihongbin100
  codepen: https://codepen.io/lihongbin100/pens/public/?grid_type=list
  more: http://www.simamedia.cn

# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
show_count: true
archive_type: 'monthly'

# Disqus 
disqus:
  enable: true
  shortname: lihb    #your name
  count: true

disqus_proxy:
  shortname: ciqu
  username: ciqu
  host: disqus-prhexoxy.ycwalker.com
  port: 443

# 腾讯云分析 http://mta.qq.com/h5/base/ctr_realtime_data?app_id=500419572
qqmta:
  sid: 500419572

# Miscellaneous
google_analytics:
favicon: https://upload.jianshu.io/users/upload_avatars/3098335/79645466-8cb0-4d4a-b855-3f80a8c86a50.jpg?imageMogr2/auto-orient/strip|imageView2/1/w/240/h/240
twitter:
google_plus:
fb_admins:
fb_app_id:
